### ISSUE TITLE
User defined primitives?

### ISSUE THREAD

**Issue by ib00** [madmann91/rt#1]
What's the best way (performance-wise) to add user-defined primitives?

Add extra information about primitive type in 'struct bvh_node' and do 
a switch statement inside 'intersect_leaf_fn' to intersect with desired type?

The alternative of grouping and sorting intersections based on primitive type
would require a lot of extra work (copying and storing data and sorting).

**Comment by madmann91** [comment]
You have those two options. I'm working right now on adding this functionality to rt, so that I can at least support quads, and triangles. The way I implement that is simply:
```c
// Generic mesh containing any primitive type
struct mesh_accel {
    void (*intersect_ray)(struct ray*, struct hit*, const struct mesh_accel*, bool);
    struct bvh* bvh;
    void* primitives;
};

#define GEN_INTERSECT_RAY_MESH_ACCEL(T, intersect_ray_primitive) \
    static inline bool intersect_ray_##T##_mesh_accel_leaf( \
        struct ray* ray, struct hit* hit, \
        const struct bvh_node* leaf, \
        const struct T* primitives, bool any) \
    { \
        bool found = false; \
        for (size_t i = leaf->first_child_or_primitive, n = i + leaf->primitive_count; i < n; ++i) { \
            if (intersect_ray_primitive(ray, hit, &primitives[i])) { \
                hit->primitive_index = i; \
                found = true; \
                if (any) \
                    return true; \
            } \
        } \
        return found; \
    } \
    static bool intersect_ray_##T##_mesh_accel_leaf_closest( \
        struct ray* ray, struct hit* hit, \
        const struct bvh_node* leaf, \
        void* intersection_data) \
    { \
        return intersect_ray_##T##_mesh_accel_leaf(ray, hit, leaf, intersection_data, false); \
    } \
    static bool intersect_ray_##T##_mesh_accel_leaf_any( \
        struct ray* ray, struct hit* hit, \
        const struct bvh_node* leaf, \
        void* intersection_data) \
    { \
        return intersect_ray_##T##_mesh_accel_leaf(ray, hit, leaf, intersection_data, true); \
    } \
    static void intersect_ray_##T##_mesh_accel( \
        struct ray* ray, struct hit* hit, \
        const struct mesh_accel* mesh_accel, \
        bool any) { \
        intersect_ray_bvh( \
            ray, hit, \
            mesh_accel->bvh, \
            any \
                ? intersect_ray_##T##_mesh_accel_leaf_any \
                : intersect_ray_##T##_mesh_accel_leaf_closest, \
            mesh_accel->primitives, \
            any); \
    }
```
Then I can just instantiate that with different primitive types, e.g.:
 ```c
GEN_INTERSECT_RAY_MESH_ACCEL(tri, intersect_ray_tri)
GEN_INTERSECT_RAY_MESH_ACCEL(quad, intersect_ray_quad)
```

**Comment by madmann91** [comment]
In general the performance of each solution depends on the scene, of course. So having one BVH per primitive type is obviously better if you have many primitives of the same type, and few of a different type. If you have as many primitives of type 1 as you have primitives of type 2, it might make sense to create a BVH that contains a "hybrid" primitive and have your intersection function choose which variant to test using a a switch/if statement. Note that if you want to do quads/triangles, you can always use degenerate quads to represent triangles (e.g. v0, v1, v2, v2 for triangle v0, v1, v2).

**Comment by ib00** [comment]
Thanks. 

Would it make sense then to have a two-level BVH? The top level just intersects
bounding boxes and the bottom level would then have a different BVH type as you
have described?

**Comment by madmann91** [comment]
Yes, it would make sense. The BVH construction is generic, so you can plug whatever primitive type you want there, including other BVHs for each mesh instance. I'm going to implement that as well. It's just going to take a bit of time.

**Comment by ib00** [comment]
Awesome! The fact that your code is C99, readable and well commented is really great.

One more performance question.

Is there a benefit to storing bbox arrays and primitive counts and indices for bvh_node separately?
So, just changing representation from AOS to SOA:

struct bvh {
    bbox3* aabbs;
    bits_t    ranges;
   .....
};

I haven't seen discussions about this.

**Comment by madmann91** [comment]
I have a blog post on this BVH stuff, that I wrote some time ago: https://madmann91.github.io/2020/12/28/bvhs-part-1.html. Long story short, the layout is designed such that each node is exactly 32 bytes, and given that the two children of a node are always packed together, the two children of a node should exactly fit into a cache line (64 bytes), which is particularly good since the traversal algorithm intersects the bounding boxes of two children together. I don't think changing the representation to SoA will give you better performance, and in fact I suspect it will give worse performance (given that the nice property of having two children exactly fit a cache line is gone), but to be honest I haven't done benchmarks with the SoA layout.
